version: "3"

services:
  web-server:
    build:
      context: .
      dockerfile: dockerfile
    image: cyber_threat_map:v1.0
    volumes:
      - ./:/src
    ports:
      - "8081:8888"
    restart: always
    depends_on:
      - redis-server

  redis-server:
    image: redis:7.4
    restart: always
